# -*- coding: utf-8 -*-
"""indentation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vog0mrPp_6k_407JOgJ3ecMzNJfc6G19
"""

def greet(name):
    if name:
        print(f"Hello, {name}!")
    else:
        print("Hello, Stranger!")

# Call the function
greet("Alice")
greet("")

